package com.s23010691.freshconnect.network;

import android.os.Handler;
import android.os.Looper;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import android.graphics.Bitmap;
import com.s23010691.freshconnect.models.Product;

import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

/*
 * Supabase Client
 * Handles all network interactions with the Supabase backend, including authentication, database operations, and storage.
 */
public class SupabaseClient {

    private static final String SUPABASE_URL = "https://bqvwafvqxwhtfkeamchs.supabase.co";
    private static final String SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdndhZnZxeHdodGZrZWFtY2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2Mzk2ODYsImV4cCI6MjA5NDIxNTY4Nn0.T9EC8lvdgMsqrg58piAC0Bf3lEhJNZOx1JELAL5YH9s";

    private static final MediaType JSON = MediaType.get("application/json; charset=utf-8");
    private final OkHttpClient client;
    private final Gson gson;
    private final Handler mainHandler;

    public static String currentAccessToken = null;
    public static String currentUserId = null;
    public static String currentUserEmail = null;

    public interface AuthCallback {
        void onSuccess();
        void onError(String error);
    }
    
    public interface UploadCallback {
        void onSuccess(String publicUrl);
        void onError(String error);
    }
    
    public interface InsertCallback {
        void onSuccess();
        void onError(String error);
    }

    /*
     * Constructor for SupabaseClient.
     * Initializes the OkHttpClient, Gson parser, and the main thread handler.
     */
    public SupabaseClient() {
        client = new OkHttpClient();
        gson = new Gson();
        mainHandler = new Handler(Looper.getMainLooper());
    }

    /*
     * Registers a new user with email and password.
     * Parameters:
     *   - email: The user's email address.
     *   - password: The user's password.
     *   - name: The user's full name.
     *   - callback: Callback to handle success or error.
     */
    public void signUp(String email, String password, String name, AuthCallback callback) {
        JsonObject jsonBody = new JsonObject();
        jsonBody.addProperty("email", email);
        jsonBody.addProperty("password", password);
        
        JsonObject data = new JsonObject();
        data.addProperty("name", name);
        jsonBody.add("data", data);

        RequestBody body = RequestBody.create(gson.toJson(jsonBody), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/auth/v1/signup")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .post(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        JsonObject resJson = gson.fromJson(bodyStr, JsonObject.class);
                        currentAccessToken = resJson.get("access_token").getAsString();
                        currentUserId = resJson.getAsJsonObject("user").get("id").getAsString();
                        currentUserEmail = email;
                    } catch (Exception e) {
                        currentUserEmail = email;
                    }
                    // Signup in auth was successful, now save to public.user table
                    saveUserDetails(currentUserId, email, name, callback);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Sign up failed: " + err));
                }
            }
        });
    }

    /*
     * Saves user details to the public user table after a successful signup.
     * Parameters:
     *   - userId: The unique ID generated by Supabase Auth.
     *   - email: The user's email.
     *   - name: The user's name.
     *   - callback: Callback to handle success or error.
     */
    private void saveUserDetails(String userId, String email, String name, AuthCallback callback) {
        JsonObject jsonBody = new JsonObject();
        if (userId != null) {
            jsonBody.addProperty("id", userId);
        }
        jsonBody.addProperty("email", email);
        jsonBody.addProperty("name", name);

        RequestBody body = RequestBody.create(gson.toJson(jsonBody), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/user")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .addHeader("Content-Type", "application/json")
                .addHeader("Prefer", "return=minimal")
                .post(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error when saving profile: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Failed to save profile: " + err));
                }
            }
        });
    }

    /*
     * Authenticates a user with email and password.
     * Parameters:
     *   - email: The user's email.
     *   - password: The user's password.
     *   - callback: Callback to handle success or error.
     */
    public void login(String email, String password, AuthCallback callback) {
        JsonObject jsonBody = new JsonObject();
        jsonBody.addProperty("email", email);
        jsonBody.addProperty("password", password);

        RequestBody body = RequestBody.create(gson.toJson(jsonBody), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/auth/v1/token?grant_type=password")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .post(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        JsonObject resJson = gson.fromJson(bodyStr, JsonObject.class);
                        currentAccessToken = resJson.get("access_token").getAsString();
                        currentUserId = resJson.getAsJsonObject("user").get("id").getAsString();
                        if (resJson.has("user") && resJson.getAsJsonObject("user").has("email")) {
                            currentUserEmail = resJson.getAsJsonObject("user").get("email").getAsString();
                        } else {
                            currentUserEmail = email;
                        }
                    } catch (Exception e) {
                        currentUserEmail = email;
                    }
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Login failed: " + err));
                }
            }
        });
    }

    /*
     * Uploads a product image to Supabase storage.
     * Parameters:
     *   - bitmap: The image bitmap to upload.
     *   - fileName: The name to save the file as.
     *   - callback: Callback returning the public URL on success.
     */
    public void uploadProductImage(Bitmap bitmap, String fileName, UploadCallback callback) {
        if (currentAccessToken == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.JPEG, 80, bos);
        byte[] bitmapData = bos.toByteArray();

        RequestBody requestBody = RequestBody.create(bitmapData, MediaType.parse("image/jpeg"));

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/storage/v1/object/product-images/" + fileName)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .post(requestBody)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    String publicUrl = SUPABASE_URL + "/storage/v1/object/public/product-images/" + fileName;
                    runOnMain(() -> callback.onSuccess(publicUrl));
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Upload failed: " + err));
                }
            }
        });
    }

    /*
     * Inserts a new product listing into the database.
     * Parameters:
     *   - product: The product object containing details.
     *   - callback: Callback to handle success or error.
     */
    public void insertProduct(Product product, InsertCallback callback) {
        if (currentAccessToken == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        RequestBody body = RequestBody.create(gson.toJson(product), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/products")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .addHeader("Content-Type", "application/json")
                .addHeader("Prefer", "return=minimal")
                .post(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Insert failed: " + err));
                }
            }
        });
    }

    public interface UserCallback {
        void onSuccess(JsonObject userJson);
        void onError(String error);
    }

    /*
     * Fetches user profile details by their email address.
     * Parameters:
     *   - email: The email to search for.
     *   - callback: Callback returning the user's JSON object.
     */
    public void fetchUserDetails(String email, UserCallback callback) {
        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/user?email=eq." + email)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        com.google.gson.JsonArray array = gson.fromJson(bodyStr, com.google.gson.JsonArray.class);
                        if (array.size() > 0) {
                            JsonObject userObj = array.get(0).getAsJsonObject();
                            runOnMain(() -> callback.onSuccess(userObj));
                        } else {
                            runOnMain(() -> callback.onError("User not found"));
                        }
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Fetch failed: " + err));
                }
            }
        });
    }

    public void fetchUserDetailsById(String id, UserCallback callback) {
        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/user?id=eq." + id)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        com.google.gson.JsonArray array = gson.fromJson(bodyStr, com.google.gson.JsonArray.class);
                        if (array.size() > 0) {
                            JsonObject userObj = array.get(0).getAsJsonObject();
                            runOnMain(() -> callback.onSuccess(userObj));
                        } else {
                            runOnMain(() -> callback.onError("User not found"));
                        }
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Fetch failed: " + err));
                }
            }
        });
    }

    public void uploadProfilePic(Bitmap bitmap, String fileName, UploadCallback callback) {
        if (currentAccessToken == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.JPEG, 80, bos);
        byte[] bitmapData = bos.toByteArray();

        RequestBody requestBody = RequestBody.create(bitmapData, MediaType.parse("image/jpeg"));

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/storage/v1/object/profile-pic/" + fileName)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .post(requestBody)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    String publicUrl = SUPABASE_URL + "/storage/v1/object/public/profile-pic/" + fileName;
                    runOnMain(() -> callback.onSuccess(publicUrl));
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Upload failed: " + err));
                }
            }
        });
    }

    public void updateUserDetails(String email, JsonObject updates, InsertCallback callback) {
        RequestBody body = RequestBody.create(gson.toJson(updates), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/user?email=eq." + email)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .addHeader("Content-Type", "application/json")
                .addHeader("Prefer", "return=minimal")
                .patch(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Update failed: " + err));
                }
            }
        });
    }

    public interface ProductsCallback {
        void onSuccess(java.util.List<Product> products);
        void onError(String error);
    }

    /*
     * Fetches a list of all products, optionally filtered by category.
     * Parameters:
     *   - category: The category to filter by, or "All" for no filter.
     *   - callback: Callback returning a list of products.
     */
    public void fetchProducts(String category, ProductsCallback callback) {
        String urlStr = SUPABASE_URL + "/rest/v1/products?select=*&order=created_at.desc";
        if (category != null && !category.isEmpty() && !category.equalsIgnoreCase("All")) {
            urlStr = SUPABASE_URL + "/rest/v1/products?category=eq." + category + "&select=*&order=created_at.desc";
        }

        Request request = new Request.Builder()
                .url(urlStr)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        java.lang.reflect.Type listType = new com.google.gson.reflect.TypeToken<java.util.ArrayList<Product>>(){}.getType();
                        java.util.List<Product> productsList = gson.fromJson(bodyStr, listType);
                        runOnMain(() -> callback.onSuccess(productsList));
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Failed to fetch products: " + err));
                }
            }
        });
    }

    public void searchProductsByName(String query, ProductsCallback callback) {
        String encodedQuery = "";
        try {
            encodedQuery = java.net.URLEncoder.encode("*" + query + "*", "UTF-8");
        } catch (java.io.UnsupportedEncodingException e) {
            encodedQuery = query;
        }
        String urlStr = SUPABASE_URL + "/rest/v1/products?name=ilike." + encodedQuery + "&select=*&order=created_at.desc";

        Request request = new Request.Builder()
                .url(urlStr)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        java.lang.reflect.Type listType = new com.google.gson.reflect.TypeToken<java.util.ArrayList<Product>>(){}.getType();
                        java.util.List<Product> productsList = gson.fromJson(bodyStr, listType);
                        runOnMain(() -> callback.onSuccess(productsList));
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Failed to search products: " + err));
                }
            }
        });
    }

    public static class BookmarkResponse {
        public String product_id;
        public Product products;
    }

    public interface BookmarkCheckCallback {
        void onSuccess(boolean isBookmarked);
        void onError(String error);
    }

    public interface BookmarksCallback {
        void onSuccess(java.util.List<Product> products);
        void onError(String error);
    }

    public void addBookmark(String productId, InsertCallback callback) {
        if (currentAccessToken == null || currentUserId == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        JsonObject bodyJson = new JsonObject();
        bodyJson.addProperty("user_id", currentUserId);
        bodyJson.addProperty("product_id", productId);

        RequestBody body = RequestBody.create(gson.toJson(bodyJson), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/saved_product")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .addHeader("Content-Type", "application/json")
                .addHeader("Prefer", "return=minimal")
                .post(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Bookmark failed: " + err));
                }
            }
        });
    }

    public void removeBookmark(String productId, InsertCallback callback) {
        if (currentAccessToken == null || currentUserId == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        String filter = "user_id=eq." + currentUserId + "&product_id=eq." + productId;

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/saved_product?" + filter)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .delete()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Remove bookmark failed: " + err));
                }
            }
        });
    }

    public void checkBookmarkStatus(String productId, BookmarkCheckCallback callback) {
        if (currentAccessToken == null || currentUserId == null) {
            runOnMain(() -> callback.onSuccess(false));
            return;
        }

        String filter = "user_id=eq." + currentUserId + "&product_id=eq." + productId + "&select=id";

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/saved_product?" + filter)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        com.google.gson.JsonArray array = gson.fromJson(bodyStr, com.google.gson.JsonArray.class);
                        runOnMain(() -> callback.onSuccess(array.size() > 0));
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    runOnMain(() -> callback.onSuccess(false));
                }
            }
        });
    }

    public void fetchBookmarkedProducts(BookmarksCallback callback) {
        if (currentAccessToken == null || currentUserId == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        String urlStr = SUPABASE_URL + "/rest/v1/saved_product?user_id=eq." + currentUserId + "&select=product_id,products(*)";

        Request request = new Request.Builder()
                .url(urlStr)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        java.lang.reflect.Type listType = new com.google.gson.reflect.TypeToken<java.util.ArrayList<BookmarkResponse>>(){}.getType();
                        java.util.List<BookmarkResponse> resList = gson.fromJson(bodyStr, listType);

                        java.util.List<Product> productsList = new java.util.ArrayList<>();
                        for (BookmarkResponse br : resList) {
                            if (br.products != null) {
                                productsList.add(br.products);
                            }
                        }
                        runOnMain(() -> callback.onSuccess(productsList));
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Failed to fetch bookmarks: " + err));
                }
            }
        });
    }

    public interface ChatsCallback {
        void onSuccess(java.util.List<com.s23010691.freshconnect.models.Chat> chats);
        void onError(String error);
    }

    public interface MessagesCallback {
        void onSuccess(java.util.List<com.s23010691.freshconnect.models.Message> messages);
        void onError(String error);
    }

    public void fetchRecentChats(ChatsCallback callback) {
        if (currentAccessToken == null || currentUserId == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        String safeCurrent = "%22" + currentUserId + "%22";
        String filter = "or=(sender_id.eq." + safeCurrent + ",receiver_id.eq." + safeCurrent + ")";
        
        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/messages?" + filter + "&select=*&order=created_at.desc")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        java.lang.reflect.Type listType = new com.google.gson.reflect.TypeToken<java.util.ArrayList<com.s23010691.freshconnect.models.Message>>(){}.getType();
                        java.util.List<com.s23010691.freshconnect.models.Message> msgsList = gson.fromJson(bodyStr, listType);
                        
                        java.util.List<com.s23010691.freshconnect.models.Chat> chatsList = new java.util.ArrayList<>();
                        java.util.Set<String> seenIds = new java.util.HashSet<>();
                        
                        for (com.s23010691.freshconnect.models.Message msg : msgsList) {
                            String otherId = msg.sender_id.equals(currentUserId) ? msg.receiver_id : msg.sender_id;
                            if (!seenIds.contains(otherId)) {
                                seenIds.add(otherId);
                                chatsList.add(new com.s23010691.freshconnect.models.Chat(otherId, msg.message, msg.created_at));
                            }
                        }
                        
                        runOnMain(() -> callback.onSuccess(chatsList));
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Failed to fetch chats: " + err));
                }
            }
        });
    }

    public void sendMessage(String receiverId, String messageText, InsertCallback callback) {
        if (currentAccessToken == null || currentUserId == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        com.s23010691.freshconnect.models.Message newMsg = new com.s23010691.freshconnect.models.Message(currentUserId, receiverId, messageText);
        RequestBody body = RequestBody.create(gson.toJson(newMsg), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/messages")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .addHeader("Content-Type", "application/json")
                .addHeader("Prefer", "return=minimal")
                .post(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Send message failed: " + err));
                }
            }
        });
    }

    public void fetchMessages(String otherUserId, MessagesCallback callback) {
        if (currentAccessToken == null || currentUserId == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        String safeCurrent = "%22" + currentUserId + "%22";
        String safeOther = "%22" + otherUserId + "%22";
        String filter = "or=(and(sender_id.eq." + safeCurrent + ",receiver_id.eq." + safeOther + ")," +
                           "and(sender_id.eq." + safeOther + ",receiver_id.eq." + safeCurrent + "))";

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/messages?" + filter + "&select=*&order=created_at.asc")
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        java.lang.reflect.Type listType = new com.google.gson.reflect.TypeToken<java.util.ArrayList<com.s23010691.freshconnect.models.Message>>(){}.getType();
                        java.util.List<com.s23010691.freshconnect.models.Message> msgsList = gson.fromJson(bodyStr, listType);
                        runOnMain(() -> callback.onSuccess(msgsList));
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Failed to fetch messages: " + err));
                }
            }
        });
    }

    public void fetchProductsByUser(String userId, ProductsCallback callback) {
        if (userId == null) {
            runOnMain(() -> callback.onError("User ID is null"));
            return;
        }
        String urlStr = SUPABASE_URL + "/rest/v1/products?user_id=eq." + userId + "&select=*&order=created_at.desc";

        Request request = new Request.Builder()
                .url(urlStr)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + SUPABASE_KEY)
                .get()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, java.io.IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws java.io.IOException {
                if (response.isSuccessful()) {
                    try {
                        String bodyStr = response.body().string();
                        java.lang.reflect.Type listType = new com.google.gson.reflect.TypeToken<java.util.ArrayList<Product>>(){}.getType();
                        java.util.List<Product> productsList = gson.fromJson(bodyStr, listType);
                        runOnMain(() -> callback.onSuccess(productsList));
                    } catch (Exception e) {
                        runOnMain(() -> callback.onError("Parsing error: " + e.getMessage()));
                    }
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Failed to fetch user products: " + err));
                }
            }
        });
    }

    public void updateProduct(String productId, JsonObject updates, InsertCallback callback) {
        if (currentAccessToken == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        RequestBody body = RequestBody.create(gson.toJson(updates), JSON);

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/products?id=eq." + productId)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .addHeader("Content-Type", "application/json")
                .addHeader("Prefer", "return=minimal")
                .patch(body)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, java.io.IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws java.io.IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Update product failed: " + err));
                }
            }
        });
    }

    public void deleteProduct(String productId, InsertCallback callback) {
        if (currentAccessToken == null) {
            runOnMain(() -> callback.onError("Not authenticated"));
            return;
        }

        Request request = new Request.Builder()
                .url(SUPABASE_URL + "/rest/v1/products?id=eq." + productId)
                .addHeader("apikey", SUPABASE_KEY)
                .addHeader("Authorization", "Bearer " + currentAccessToken)
                .delete()
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, java.io.IOException e) {
                runOnMain(() -> callback.onError("Network error: " + e.getMessage()));
            }

            @Override
            public void onResponse(Call call, Response response) throws java.io.IOException {
                if (response.isSuccessful()) {
                    runOnMain(callback::onSuccess);
                } else {
                    String err = parseError(response.body().string());
                    runOnMain(() -> callback.onError("Delete product failed: " + err));
                }
            }
        });
    }

    /*
     * Helper to run callbacks on the main UI thread.
     * Parameters:
     *   - runnable: The code block to execute on the main thread.
     */
    private void runOnMain(Runnable runnable) {
        mainHandler.post(runnable);
    }

    private String parseError(String responseBody) {
        try {
            JsonObject jsonObject = gson.fromJson(responseBody, JsonObject.class);
            if (jsonObject.has("error_description")) {
                return jsonObject.get("error_description").getAsString();
            } else if (jsonObject.has("msg")) {
                return jsonObject.get("msg").getAsString();
            } else if (jsonObject.has("message")) {
                return jsonObject.get("message").getAsString();
            }
        } catch (Exception e) {
            // fallback
        }
        return "Unknown error";
    }
}
